apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: rguske-rhel9-bridge-gitops
# namePrefix: coe-

resources:
  - ../../base

patches:
- path: patch-network.yaml
- path: patch-storage.yaml