apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/linux-rhel9-bridge-network.yaml

patches:
- path: patch-storage-and-network.yaml
  target:
    kind: VirtualMachine
    name: rguske-rhel9-bridge-gitops-vm1